name: "todo-app"

entry: "src/main.ts"

output:
  path: "build/"
  js:
    path: "js"
  css:
    path: "css"
  images:
    path: "images"
  fonts:
    path: "fonts"

assets:
  icons:
    iconPath: "resources/icons/favicons/favicon.svg"
    output:
      path: "icons/"

report:
  path: "reports/webpack.bundle-report.html"
